apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: social-media
type: Opaque
data:
  # This is just a sample secret key, in production you should use a properly generated key
  # The value is base64 encoded: echo -n "09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7" | base64
  SECRET_KEY: MDlkMjVlMDk0ZmFhNmNhMjU1NmM4MTgxNjZiN2E5NTYzYjkzZjcwOTlmNmYwZjRjYWE2Y2Y2M2I4OGU4ZDNlNw==
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: social-media
type: Opaque
data:
  # The values are base64 encoded: echo -n "postgres" | base64
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  POSTGRES_DB: c29jaWFsbWVkaWE=
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secrets
  namespace: social-media
type: Opaque
data:
  # The value is base64 encoded: echo -n "admin" | base64
  GF_SECURITY_ADMIN_PASSWORD: YWRtaW4=